// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDEQVl0dS4Mq3zlvtQ-ss3VxkLgvsd58g',
    appId: '1:745210326206:web:346507d7567b5d4a8502ef',
    messagingSenderId: '745210326206',
    projectId: 'react-redux-d0f95',
    authDomain: 'react-redux-d0f95.firebaseapp.com',
    databaseURL: 'https://react-redux-d0f95-default-rtdb.firebaseio.com',
    storageBucket: 'react-redux-d0f95.appspot.com',
    measurementId: 'G-ZZEXE69KBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASOlIU0i2tw1DTksyQyoKn5kvF-cd-RMc',
    appId: '1:745210326206:android:9cdd44cfc1b263518502ef',
    messagingSenderId: '745210326206',
    projectId: 'react-redux-d0f95',
    databaseURL: 'https://react-redux-d0f95-default-rtdb.firebaseio.com',
    storageBucket: 'react-redux-d0f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZxSXaR7HmlJxis2lQk-KpD3A9CZTRMq8',
    appId: '1:745210326206:ios:261cc4bbbea24e058502ef',
    messagingSenderId: '745210326206',
    projectId: 'react-redux-d0f95',
    databaseURL: 'https://react-redux-d0f95-default-rtdb.firebaseio.com',
    storageBucket: 'react-redux-d0f95.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZxSXaR7HmlJxis2lQk-KpD3A9CZTRMq8',
    appId: '1:745210326206:ios:3e3c31da79985f698502ef',
    messagingSenderId: '745210326206',
    projectId: 'react-redux-d0f95',
    databaseURL: 'https://react-redux-d0f95-default-rtdb.firebaseio.com',
    storageBucket: 'react-redux-d0f95.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
